apiVersion: v1
kind: Service
metadata:
  name: splunk-server
  labels:
    {{- include "splunk-sli-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "splunk-sli-provider.selectorLabels" . | nindent 4 }}
