{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-sli-provider.serviceAccountName" . }}
  labels:
    {{- include "splunk-sli-provider.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
{{- if .Values.serviceAccount.createRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-read-secret-splunk
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-splunk-sli-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-read-secret-splunk
subjects:
  - kind: ServiceAccount
    name: {{ include "splunk-sli-provider.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- $splunk_namespace := (include "splunk-sli-provider.namespace" .) }}
{{- $splunk_namespace_am := (include "splunk-am-service.namespace" .) }}
{{- $namespaces := dict $splunk_namespace nil $splunk_namespace_am  nil }}
{{- $release_namespace := .Release.Namespace }}
{{- range $namespace, $_ := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-splunk-sli-provider
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-splunk-sli-provider
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-splunk-sli-provider
subjects:
  - kind: ServiceAccount
    name: keptn-splunk-sli-provider
    namespace: {{ $release_namespace }}

{{- end }}
{{- end }}
{{- end }}
